version: '4'
services:
  order_mysql:
    image: mysql:8.3.0
    container_name: datarest_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
      - datarest_mysql_data:/var/lib/mysql
      #- ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  datarest_mysql_data:
